export const CREATE_CONSUMPTION = 'CREATE_CONSUMPTION';
export const UPDATE_CONSUMPTION = 'UPDATE_CONSUMPTION';
export const DELETE_CONSUMPTION = 'DELETE_CONSUMPTION';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const SET_BUDGET = 'SET_BUDGET';